import type { Metadata } from "next";
import "./globals.css";

import { Inter} from 'next/font/google';
import Header from "@/sections/header";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Torque Fest ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} dark`}>
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
