import type { Metadata } from "next";
import "./globals.css";

import { Inter, Geist, Geist_Mono, Space_Grotesk} from 'next/font/google';
import Header from "@/sections/header";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-grotesk',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Torque Fest ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${spaceGrotesk.variable} dark`}>
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
